### ISSUE TITLE
Conv layers used in ED-TCN

### ISSUE THREAD

**Issue by SenJia** [colincsl/TemporalConvolutionalNetworks#10]
Hi Colin, thanks a lot for sharing this code, really helpful. Can I ask question about the implementation of you ED-TCN. Based on your paper(CVPR17), figure 1 shows there are two conv layers in the encoder and the decoder. However, your paper says "(e.g., 3 in the encoder)", and I can only see one conv layer in the encoder, "Convolution1D" line 81, tf_models.py. I might miss something there, I wonder which one is correct? Thanks.

**Comment by colincsl** [comment]
Hi! Line 81 is part of a `for` loop which results in `n_layers` conv layers in the encoder. The paper provides results when using different numbers of layers in the encoder/decoder.

**Comment by SenJia** [comment]
Hi, Thank you for the clarification, I missed that part. Thanks again for sharing the code, very interesting study!
