### ISSUE TITLE
can't download 50 salads features

### ISSUE THREAD

**Issue by wanduoz** [colincsl/TemporalConvolutionalNetworks#12]
Hello, I would like to download the features of the 50 salada dataset. I want to train this model for academic research. I have submitted the request but have not received feedback. Can these trained features still be downloaded? Thank you for your reply.

**Comment by colincsl** [comment]
Closing. You've been added to the access list on google drive.

**Comment by wanduoz** [comment]
Hi, I still don't have permission to access the data. My google email is zzzwwwdxd@gmail.com

https://drive.google.com/open?id=0B2EDVAtaGbOtUTJpdWxOc0pEaEk

![image](https://github.com/colincsl/TemporalConvolutionalNetworks/assets/33130310/43be3079-3f97-4586-a5d5-0eed06c1e02e)

**Comment by colincsl** [comment]
Done

**Comment by wanduoz** [comment]
I can download the feature now. Thank you!
