### ISSUE TITLE
Accelerometer features from 50 salads dataset

### ISSUE THREAD

**Issue by Harsharma2308** [colincsl/TemporalConvolutionalNetworks#6]
Hi
1. Can you tell if the accelerometer features from 50 salads mid-level dataset(which I saw is a 30x1 vector at a timestep) are raw acceleration values or have they been processed? 
2. Assuming the 30x1 vector has 3 subsequent values as acc_x,acc_y ,acc_z from each of the IMUs (which I believe were 8), are there 10 sensors or some values are expected to be empty?

I just want to make sure if I can use this for IMU data I have for action detection.

**Comment by colincsl** [comment]
Hi Harsh, 

1. This data has been post processed. 
2.  In total there are 10 accelerometers which are located on the plate, pepper dispenser, bowl, oil bottle, large spoon, dressing glass, knife, peeler, small spoon and chopping board

I believe my dissertation has more of those details if you are interested: https://drive.google.com/file/d/0B2EDVAtaGbOteThEWF9HMVI1ZE0/view?usp=sharing <https://drive.google.com/file/d/0B2EDVAtaGbOteThEWF9HMVI1ZE0/view?usp=sharing>

**Comment by Harsharma2308** [comment]
Thanks for your reply. I will close this now.
