### ISSUE TITLE
How to interpret the output.

### ISSUE THREAD

**Issue by ghost** [colincsl/TemporalConvolutionalNetworks#8]
> id@ipadress:# python3 code/TCN_main.py
> Using TensorFlow backend.
> 2020-06-22 02:48:46.974129: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> /workspace/code/utils.py:124: NumbaWarning: 
> Compilation is falling back to object mode WITH looplifting enabled because Function "partition_latent_labels" failed type inference due to: Untyped global name 'segment_intervals': cannot determine Numba type of <class 'function'>
> 
> File "code/utils.py", line 130:
> def partition_latent_labels(Yi, n_latent):
>     <source elided>
>     Zi = Yi.copy()
>     intervals = segment_intervals(Yi)
>     ^
> 
>   @jit("int64[:](int64[:], int64)")
> /workspace/code/utils.py:124: NumbaWarning: 
> Compilation is falling back to object mode WITHOUT looplifting enabled because Function "partition_latent_labels" failed type inference due to: Untyped global name 'segment_intervals': cannot determine Numba type of <class 'function'>
> 
> File "code/utils.py", line 130:
> def partition_latent_labels(Yi, n_latent):
>     <source elided>
>     Zi = Yi.copy()
>     intervals = segment_intervals(Yi)
>     ^
> 
>   @jit("int64[:](int64[:], int64)")
> /usr/local/lib/python3.6/dist-packages/numba/core/object_mode_passes.py:178: NumbaWarning: Function "partition_latent_labels" was compiled in object mode without forceobj=True, but has lifted loops.
> 
> File "code/utils.py", line 126:
> def partition_latent_labels(Yi, n_latent):
>     if n_latent == 1:
>     ^
> 
>   state.func_ir.loc))
> /usr/local/lib/python3.6/dist-packages/numba/core/object_mode_passes.py:188: NumbaDeprecationWarning: 
> Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.
> 
> For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
> 
> File "code/utils.py", line 126:
> def partition_latent_labels(Yi, n_latent):
>     if n_latent == 1:
>     ^
> 
>   state.func_ir.loc))
> /workspace/code/metrics.py:143: NumbaWarning: 
> Compilation is falling back to object mode WITH looplifting enabled because Function "levenstein_" failed type inference due to: No implementation of function Function(<built-in function zeros>) found for signature:
>  
>  >>> zeros(list(int64), Function(<class 'float'>))
>  
> There are 2 candidate implementations:
>   - Of which 2 did not match due to:
>   Overload in function 'zeros': File: <built-in>: Line <N/A>.
>     With argument(s): '(list(int64), Function(<class 'float'>))':
>    No match.
> 
> During: resolving callee type: Function(<built-in function zeros>)
> During: typing of call at /workspace/code/metrics.py (147)
> 
> 
> File "code/metrics.py", line 147:
> def levenstein_(p,y, norm=False):
>     <source elided>
>     n_col = len(y)
>     D = np.zeros([m_row+1, n_col+1], np.float)
>     ^
> 
>   @jit("float64(int64[:], int64[:], boolean)")
> /workspace/code/metrics.py:143: NumbaWarning: 
> Compilation is falling back to object mode WITHOUT looplifting enabled because Function "levenstein_" failed type inference due to: cannot determine Numba type of <class 'numba.core.dispatcher.LiftedLoop'>
> 
> File "code/metrics.py", line 148:
> def levenstein_(p,y, norm=False):
>     <source elided>
>     D = np.zeros([m_row+1, n_col+1], np.float)
>     for i in range(m_row+1):
>     ^
> 
>   @jit("float64(int64[:], int64[:], boolean)")
> /usr/local/lib/python3.6/dist-packages/numba/core/object_mode_passes.py:178: NumbaWarning: Function "levenstein_" was compiled in object mode without forceobj=True, but has lifted loops.
> 
> File "code/metrics.py", line 145:
> def levenstein_(p,y, norm=False):
>     m_row = len(p)    
>     ^
> 
>   state.func_ir.loc))
> /usr/local/lib/python3.6/dist-packages/numba/core/object_mode_passes.py:188: NumbaDeprecationWarning: 
> Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.
> 
> For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
> 
> File "code/metrics.py", line 145:
> def levenstein_(p,y, norm=False):
>     m_row = len(p)    
>     ^
> 
>   state.func_ir.loc))
> # Feat: 18
> mid_video_SVM
> /usr/local/lib/python3.6/dist-packages/numba/core/ir_utils.py:2031: NumbaPendingDeprecationWarning: 
> Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'p' of function 'levenstein_'.
> 
> For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
> 
> File "code/metrics.py", line 153:
> def levenstein_(p,y, norm=False):
>     <source elided>
> 
>     for j in range(1, n_col+1):
>     ^
> 
>   warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
> /usr/local/lib/python3.6/dist-packages/numba/core/ir_utils.py:2031: NumbaPendingDeprecationWarning: 
> Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'y' of function 'levenstein_'.
> 
> For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
> 
> File "code/metrics.py", line 153:
> def levenstein_(p,y, norm=False):
>     <source elided>
> 
>     for j in range(1, n_col+1):
>     ^
> 
>   warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
> Trial Split_1: accuracy:61.51, edit_score:21.64, overlap_f1:30.84
> 
> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   return array(a, dtype, copy=False, order=order, subok=True)
> code/TCN_main.py:229: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   P_test_ = np.array(P_test)/float(n_classes-1)
> code/TCN_main.py:230: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   y_test_ = np.array(y_test)/float(n_classes-1)
> # Feat: 18
> mid_video_SVM
> Trial Split_1: accuracy:61.51, edit_score:21.64, overlap_f1:30.84
> Trial Split_2: accuracy:53.48, edit_score:20.79, overlap_f1:27.2
> 
> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   return array(a, dtype, copy=False, order=order, subok=True)
> code/TCN_main.py:229: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   P_test_ = np.array(P_test)/float(n_classes-1)
> code/TCN_main.py:230: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   y_test_ = np.array(y_test)/float(n_classes-1)
> # Feat: 18
> mid_video_SVM
> Trial Split_1: accuracy:61.51, edit_score:21.64, overlap_f1:30.84
> Trial Split_2: accuracy:53.48, edit_score:20.79, overlap_f1:27.2
> Trial Split_3: accuracy:50.36, edit_score:21.9, overlap_f1:28.03
> 
> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   return array(a, dtype, copy=False, order=order, subok=True)
> code/TCN_main.py:229: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   P_test_ = np.array(P_test)/float(n_classes-1)
> code/TCN_main.py:230: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   y_test_ = np.array(y_test)/float(n_classes-1)
> # Feat: 18
> mid_video_SVM
> Trial Split_1: accuracy:61.51, edit_score:21.64, overlap_f1:30.84
> Trial Split_2: accuracy:53.48, edit_score:20.79, overlap_f1:27.2
> Trial Split_3: accuracy:50.36, edit_score:21.9, overlap_f1:28.03
> Trial Split_4: accuracy:51.03, edit_score:20.17, overlap_f1:27.71
> 
> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   return array(a, dtype, copy=False, order=order, subok=True)
> code/TCN_main.py:229: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   P_test_ = np.array(P_test)/float(n_classes-1)
> code/TCN_main.py:230: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   y_test_ = np.array(y_test)/float(n_classes-1)
> # Feat: 18
> mid_video_SVM
> Trial Split_1: accuracy:61.51, edit_score:21.64, overlap_f1:30.84
> Trial Split_2: accuracy:53.48, edit_score:20.79, overlap_f1:27.2
> Trial Split_3: accuracy:50.36, edit_score:21.9, overlap_f1:28.03
> Trial Split_4: accuracy:51.03, edit_score:20.17, overlap_f1:27.71
> Trial Split_5: accuracy:58.34, edit_score:22.66, overlap_f1:29.69
> 
> /usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   return array(a, dtype, copy=False, order=order, subok=True)
> code/TCN_main.py:229: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   P_test_ = np.array(P_test)/float(n_classes-1)
> code/TCN_main.py:230: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>   y_test_ = np.array(y_test)/float(n_classes-1)
> 
> All: accuracy:54.94 edit_score:21.43 overlap_f1:28.69
> Trial Split_1: accuracy:61.51, edit_score:21.64, overlap_f1:30.84
> Trial Split_2: accuracy:53.48, edit_score:20.79, overlap_f1:27.2
> Trial Split_3: accuracy:50.36, edit_score:21.9, overlap_f1:28.03
> Trial Split_4: accuracy:51.03, edit_score:20.17, overlap_f1:27.71
> Trial Split_5: accuracy:58.34, edit_score:22.66, overlap_f1:29.69
> 
>

I run the code TCN_main.py with 50Salads and your features.
Is this running fine? or How should I fix this?

**Comment by colincsl** [comment]
It looks like there were changes in the library Numba. Perhaps you have to use an older version. 

It might be worth cross checking the results with those in the paper. If they're the same then it should fine even with the warnings.

**Comment by ghost** [comment]
Thanks. What Numba version is yours?

**Comment by colincsl** [comment]
I haven't used this code in years so unfortunately I'm not sure. Sorry!
